### ISSUE TITLE
Problem with UILabel when \n is used

### ISSUE THREAD

**Issue by Domsware** [Raizlabs/BonMot#291] opened 2017-06-02 19:28 UTC
I want to use such string `Line 1\nLine 2` to display 2 lines on `UILabel`.

Only the first line is displayed.

I've already tested a lot of `UILabel` related stuff like `linesNumber`.  

XML parsing is in use in this string:
`<tag1>Line 1</tag1>\n<tag2>Line 2</tag2>`

## An UILabel problem
After crawling the web for few hours this appears to be some weird behavior of `UILabel`.i.e. using Storyboard I can insert line feed (over Carriage return?) by ALT+RETURN keys and it work. But using `\n`don't...

## Can BonMot help?
Maybe by using a special character:  
`<tag1>Line 1</tag1><BON:someSpecialCharacter/><tag2>Line 2</tag2>`

**Comment by ZevEisenberg** [comment] 2017-06-03 02:14
A `UILabel` with `numberOfLines = 0` should work with a `\n` character. For example, the following code works for me in an iOS Playground:

```swift
import UIKit
import PlaygroundSupport

let label = UILabel()
label.numberOfLines = 0
label.text = "foo\nbar"
label.backgroundColor = .white
label.textColor = .black
label.sizeToFit()

PlaygroundPage.current.liveView = label
```

I'm not sure what the problem is. Can you set the contents of your label to the literal string `"Line 1\nLine 2"`, and see what happens? Is there a chance you have an Auto Layout constraint conflict that is causing the label to be compressed vertically?

**Comment by Domsware** [comment] 2017-06-03 10:09
This playground also work for me. As it as already worked numerous times in other project.



## On my current project
Setting `UILabel` contents to "Line 1\nLine 2" doesn't work.

And I do not explicity use Auto Layout on this label. To be sure I removed all constraints on this label without effect.

I finally solved this problem by using a `UITextView` instead of `UILabel`.

## Tests on StoryBoard
As I wrote before, I also run tests using StoryBoard. I've created 2 `UILabel` and set their content in StoryBoard dedicated field:

1. `Label 1\nhello` with `\n` created by ALT+RETURN
<img width="214" alt="capture d ecran 2017-06-03 a 11 23 09" src="https://cloud.githubusercontent.com/assets/385357/26752416/78206158-484f-11e7-97e7-67a0d6fbbdb8.png">

2. `Label 2\nhello` with explicit `\n`
<img width="210" alt="capture d ecran 2017-06-03 a 11 23 16" src="https://cloud.githubusercontent.com/assets/385357/26752418/822ab2fc-484f-11e7-84e1-3e1fca940cdd.png">

I've created a brand new project, with Auto Layout off. So there must not have any interferences from any external libraries, nor AutoLayout. Here is the rendering.
<img width="245" alt="capture d ecran 2017-06-03 a 11 22 50" src="https://cloud.githubusercontent.com/assets/385357/26752420/8734fa50-484f-11e7-8e9a-2faac37dc1c5.png">

I then add a third label and configure it on controller, not on Story Board:
``` Swift
label3.numberOfLines = 0
label3.text = "Label3\nhello"
```

And it work!
<img width="188" alt="capture d ecran 2017-06-03 a 11 54 55" src="https://cloud.githubusercontent.com/assets/385357/26752578/822e0886-4853-11e7-820e-5c7193459f17.png">

## Conclusion
There is something weird inside my project. I don't know where it comes from but it leads to wrong behavior using `UILabel`. I found there are a lot of weird cases using `\n` with `UILabel` on internet.

**Comment by ZevEisenberg** [comment] 2017-06-05 14:31
@Domsware glad you got it figured out! I'm going to close this issue, because it doesn't sound like it's BonMot-related, but please feel free to open other issues if you have any other questions, or can think of ways to make BonMot better!

**Closed by ZevEisenberg** 2017-06-05 14:31 UTC

**Comment by t9mike** [comment] 2019-04-22 05:13
Old thread, but for anyone researching auto size and embedded newlines. The current width of the frame sets the maximum width when sizeToFit() is called. So my use, I had to ensure I reset frame width to a large number before calling sizeToFit().

**Comment by vw2k3** [comment] 2019-07-05 07:28
@ghost Thank you for the conclusion! It helps a lot
